baseURL = 'https://toastbits.dev'
languageCode = "en-GB"
theme = ["hugo-redirect", "hugo-theme-monochrome"]
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
color_scheme = "dark"
enable_toc = true
enable_collapsible_toc = true
enable_collapsible_changelogs = true
enable_site_search = true
enable_zooming_js = true

[outputs]
home = ["HTML", "JSON"]
page = ["HTML", "JSON"]

[languages]
  [languages.en]
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    title = "ToastBits"
    navbar_title = """\
      <div style="display: flex; align-items: center;">
        ~$&nbsp;

        <div style="color: var(--color-text-title);">
          toaster
        </div>

        <div style="font-size: 0.7em;">
          @toastbits.dev
        </div>
        </div>
    """
    #navbar_html = '<a href="https://github.com/toasterofbread"><img src="/github-mark-white.svg" height=15px style="margin: auto; display: block;"></img></a>'
    weight = 2

    [languages.en.params]
        author = "Talo Halton"
        footer = "Built with 愛 using <a href='https://github.com/gohugoio/hugo'>Hugo</a>, <a href='https://github.com/kaiiiz/hugo-theme-monochrome'>Monochrome</a>, and <a href='https://github.com/catppuccin/catppuccin'>Catppuccin</a>."

    [[languages.en.menu.navbar]]
      identifier = "root"
      name = "root"
      pageRef = "/en/"
      weight = 1

    [[languages.en.menu.navbar]]
        identifier = "projects"
        name = "/projects"
        pageRef = "/en/projects/"
        weight = 2

    [[languages.en.menu.navbar]]
      identifier = "about"
      name = "/about"
      pageRef = "/en/about"
      weight = 3

    [[languages.en.menu.navbar]]
      identifier = "github"
      name = "/github"
      pageRef = "/github"
      weight = 4

  [languages.ja]
    languageCode = 'ja-JP'
    languageDirection = 'ltr'
    languageName = '日本語'
    title = 'ToastBits'
    weight = 2

    [languages.ja.params]
        author = "ホートン太郎"
        footer = "Built with 愛 using <a href='https://github.com/gohugoio/hugo'>Hugo</a> and <a href='https://github.com/kaiiiz/hugo-theme-monochrome'>Monochrome</a>."

    [[languages.en.menu.navbar]]
      identifier = "root"
      name = "root"
      url = "/"
      weight = 1

    [[languages.en.menu.navbar]]
        identifier = "projects"
        name = "/projects"
        url = "/en/projects/"
        weight = 2

    [[languages.en.menu.navbar]]
      identifier = "about"
      name = "/about"
      url = "/en/about"
      weight = 3

    [[languages.en.menu.navbar]]
      identifier = "github"
      name = "/github"
      url = "/github"
      weight = 4
