baseURL = 'http://localhost'
languageCode = "en-GB"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
enable_toc = true
enable_collapsible_toc = true
enable_collapsible_changelogs = true
enable_site_search = true
color_scheme = "dark"

[languages]
  [languages.en]
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    title = "toasterofbread"
    navbar_title = '<div style="display: flex; align-items: center;">toasterofbread <a href="https://github.com/toasterofbread"><img src="/github-mark-white.svg" height=24px style="padding-left: 10px; margin: auto; display: block;"></img></a></div>'
    weight = 2
  
    [languages.en.params]
        author = "Talo Halton"
        footer = "Built with 愛 using <a href='https://github.com/gohugoio/hugo'>Hugo</a>, <a href='https://github.com/kaiiiz/hugo-theme-monochrome'>Monochrome</a>, and <a href='https://github.com/catppuccin/catppuccin'>Catppuccin</a>"
  
    [[languages.en.menu.navbar]]
        identifier = "projects"
        name = "Projects"
        url = "/en/projects/"
        weight = 1

  [languages.ja]
    languageCode = 'ja-JP'
    languageDirection = 'ltr'
    languageName = '日本語'
    title = 'toasterofbread'
    weight = 2

    [languages.ja.params]
        author = "ホートン太郎"
        footer = "Built with 愛 using <a href='https://github.com/gohugoio/hugo'>Hugo</a> and <a href='https://github.com/kaiiiz/hugo-theme-monochrome'>Monochrome</a>"

    [[languages.ja.menu.navbar]]
        identifier = "projects"
        name = "作品"
        url = "/ja/projects/"
        weight = 1
